# -*- coding: utf-8 -*-
"""Math345Proj1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JW1Bh2_aA3KhTR2YCXe3FYaAtsDEtOpP
"""

import numpy as np
import math

company1_seniority = [25, 16, 3]
company1_compensation = [250000, 60000, 40000]
company2_seniority = [1, 2, 3, 5, 8, 10]
company2_compensation = [750000, 870000, 940000, 1220000, 1750000, 2000000]

def compensation_model(seniority, min_comp, max_comp, midpoint, steepness):

    # r = range of salary
    r = max_comp - min_comp
    # growth rate
    k = 1 / (1 + math.exp(-steepness * (seniority - midpoint)))

    return min_comp + r * k

percentage_tot = 0
for i, seniority in enumerate(company1_seniority):
    if seniority > 16:
      midpoint = 9
      steepness = 1
    elif seniority < 16 & seniority > 3:
      midpoint = 13
      steepness = 0.1
    else:
      midpoint = 22
      steepness = 0.37
    prediction = compensation_model(seniority, min(company1_compensation), max(company1_compensation), midpoint, steepness)
    actual = company1_compensation[i]
    difference = prediction - actual
    percentage_diff = abs((difference / actual) * 100)
    percentage_tot += percentage_diff

    print(f"Seniority: {seniority} years")
    print(f"Actual Compensation: ${actual:,.2f}")
    print(f"Predicted Compensation: ${prediction:,.2f}")
    print(f"Percentage Difference: {percentage_diff:.2f}%\n")

mean_percentage = (percentage_tot)/ len(company1_compensation)
print(f"Mean Percentage Difference: {percentage_diff:.2f}%\n")

for i, seniority in enumerate(company2_seniority):
    prediction = compensation_model(seniority, min(company2_compensation), max(company2_compensation), midpoint=5.5, steepness=0.67)
    actual = company2_compensation[i]
    difference = prediction - actual
    percentage_diff = abs((difference / actual) * 100)
    print(f"Seniority: {seniority} years")
    print(f"Actual Compensation: ${actual:,.2f}")
    print(f"Model Predicted Compensation: ${prediction:,.2f}")
    print(f"Percentage Difference: {percentage_diff:.2f}%\n")